# App name (replace with your desired name or Fly.io will generate one)
app = "xavierback-fly"

# Primary region for deployment (e.g., 'iad' for US East)
primary_region = "iad"

# Build configuration
[build]
  dockerfile = "Dockerfile"

# Environment variables
[env]
  PORT = "8080"

# HTTP service configuration
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false  # Keeps free tier VM running
  auto_start_machines = true
  min_machines_running = 1    # Ensures 1 VM is always active

# Optional: Resource limits for free tier
[processes]
  app = ""

[deploy]
  release_command = ""
