app = "xavier-back"  # Matches your error message’s app name
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FLASK_ENV = "production"
  LOG_LEVEL = "INFO"

# Explicitly define the web process via http_service
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]  # Explicitly link to the 'web' process

[http_service.concurrency]
  type = "requests"
  soft_limit = 20
  hard_limit = 25
