"""Add QuestionAnalytics model

Revision ID: 212c3c65d23d
Revises: 103e110092a4
Create Date: 2024-11-09 15:26:54.582597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212c3c65d23d'
down_revision = '103e110092a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_analytics', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
